### PR TITLE
upgrade to SynapseAI 1.18 version

### PR DESCRIPTION
**Pull request by kaixuanliu**

### CODE REVIEW

**Comment by kaixuanliu** [comment]
For model [BAAI/bge-large-en-v1.5](https://huggingface.co/BAAI/bge-large-en-v1.5), best throughput(single client send requests) for 1.17.1 is:
```
batch size:                              128
Mean latency (ms):                       101.52
Median latency (ms):                     97.10
P99 latency (ms):                        157.82
Throughput (sentences/s):                1258.88
```
and for 1.18.0, the result is:
```
batch size:                              128 
Mean latency (ms):                       102.70  
Median latency (ms):                     98.83  
P99 latency (ms):                        161.65  
Throughput (sentences/s):                1244.59
```

**Comment by kaixuanliu** [comment]
@regisss , pls help review

**Comment by kaixuanliu** [comment]
@regisss , Hi, Can you help do the 1.18 release? Internal collaborators are asking for this.

**Comment by yao-matrix** [comment]
@mandy-li, could you help on this? Thx

**Review by regisss — APPROVED** [review]

**Pull request merged**
