### PR TITLE
Rebase 1.5.0

### PR DESCRIPTION
**Pull request by pi314ever**
# What does this PR do?

This PR rebases from mainline's [v1.5.0](https://github.com/huggingface/text-embeddings-inference/tree/v1.5.0) tag to habana-main. A better implementation of #27. 

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by kaixuanliu** [comment]
@regisss , Pls help review. Do you think it is necessary to be in 1.17 release?

**Review by regisss — APPROVED** [review]
LGTM! There's a merge conflict to solve it seems.

**Comment by regisss** [comment]
> @regisss , Pls help review. Do you think it is necessary to be in 1.17 release?

It seems this PR is not that big so I think we can merged it before releasing.

**Comment by regisss** [comment]
@kaixuanliu @pi314ever I released the new Docker image [here](https://github.com/huggingface/tei-gaudi/pkgs/container/tei-gaudi) and the release notes [there](https://github.com/huggingface/tei-gaudi/releases/tag/v1.5.0).

**Pull request merged**
