### PR TITLE
Update SynapseAI 1.17.0

### PR DESCRIPTION
**Pull request by pi314ever**
# What does this PR do?

This PR updates the supported versions to SynapseAI 1.17.0 and Optimum Habana 1.13 (with cascading dependencies). I have validated this to work with `Dockerfile-hpu`.

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by kaixuanliu** [comment]
@regisss , pls help review.

**Review by regisss — APPROVED** [review]
LGTM!

**Comment by regisss** [comment]
I'll release a new Docker image tomorrow

**Comment by regisss** [comment]
@pi314ever Have you compared the perf before and after PR?

**Comment by pi314ever** [comment]
@regisss I'll perform the benchmarks and post a summary today.

**Comment by pi314ever** [comment]
@regisss Overall, performance is within variance between 1.16.1 and 1.17.0 snapshots.

**BAAI/bge-large-en-v1.5**
Optimal throughput single threaded: **1529.43 sentences/sec @ batch size = 128 (1.17.0)** vs  1495.96 sentences/sec @ batch size = 256 (1.16.1)
Average latency for batch size 1: **4.51 ms / batch (1.17.0)** vs 4.58 ms / batch (1.16.1)
P99 latency for batch size 1: **4.99 ms / batch (1.17.0)** vs 5.49 ms / batch (1.16.1)
Average latency for batch size 2: 7.39 ms / batch (1.17.0) vs **7.29 ms / batch (1.16.1)**
P99 latency for batch size 2: 8.1 ms / batch (1.17.0) vs **8.04 ms / batch (1.16.1)**

**Comment by kaixuanliu** [comment]
@regisss Hi, Can you help do the 1.17 release?

**Pull request merged**
